name: anima
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  get_storage: ^2.1.1
  get: ^4.6.6 

  cupertino_icons: ^1.0.2
  pocketbase: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/

  